/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static project.ChooseTrip.statment;
import static project.Register.conn;

/**
 *
 * @author Dell
 */
public class Add_tour extends javax.swing.JFrame {

    /**
     * Creates new form Add_tour
     */
    static Connection conn;
    static Statement statment;
    static String query;
    sqlconn con=sqlconn.getconnection();
    public Add_tour() {
        initComponents();
        
            TourGuide tg=new TourGuide();
            String[] name=tg.getTour_available();
            for(int i=0;i<name.length;i++)
            {   
                jComboBox1.addItem(name[i]);  
            }
         
         
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idoftrip = new javax.swing.JTextField();
        nameoftrip = new javax.swing.JTextField();
        numberofclient = new javax.swing.JTextField();
        priceoftrip = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Dateoftrip = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        jLabel1.setText("Add tour ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 0, 219, -1));

        idoftrip.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        idoftrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idoftripActionPerformed(evt);
            }
        });
        getContentPane().add(idoftrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 54, 127, 34));

        nameoftrip.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        getContentPane().add(nameoftrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 200, 127, -1));

        numberofclient.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        getContentPane().add(numberofclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 373, 130, -1));

        priceoftrip.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        getContentPane().add(priceoftrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 429, 130, -1));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel2.setText("Number of People");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 377, -1, 22));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel3.setText("Name");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 202, 87, 26));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel4.setText("ID");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 87, 32));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel5.setText("price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 433, 75, 29));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 480, 152, -1));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel6.setText("Category");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, 91, 37));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel7.setText("Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, 75, 30));

        Dateoftrip.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        getContentPane().add(Dateoftrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 152, 127, -1));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel8.setText("Tour Guide");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 316, 111, 39));

        jComboBox1.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 320, 127, -1));

        jComboBox2.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adventure", "Cultural", "Religious", "Safari_Holidays" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 105, 127, 36));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel9.setText("Sites");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 273, 87, 22));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 248, 127, 62));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\back4.jpeg")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 430, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idoftripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idoftripActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_idoftripActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==jButton1)
        {
            Trip_Factory  tf= new Trip_Factory();
            Trips t=tf.Get_Trip(jComboBox2.getSelectedItem().toString());
            Employee emp= new Employee();
            try {
               
                t.setCategoryName(jComboBox2.getSelectedItem().toString());
                
                t.setDate(Dateoftrip.getText());
                t.setGuidetour(jComboBox1.getSelectedItem().toString());
                t.setId(Integer.valueOf(idoftrip.getText()));
                t.setNumber_of_tourists(Integer.valueOf(numberofclient.getText()));
                t.setCount_of_tourists(0);
                t.setPrice(Integer.valueOf(priceoftrip.getText()));
                t.setTotal_profit(t.getPrice()*t.getCount_of_tourists());
                t.setTrip_name(nameoftrip.getText());
                t.setSites(jTextArea1.getText());
                 emp.Add_trip(t);
                 dispose();
                 Menu_employee m= new Menu_employee();
                 m.show();
                 
            } catch (SQLException ex) {
                Logger.getLogger(Add_tour.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        /*if(evt.getSource()==jButton1)
        {
            try{
            
            conn=con.connect();
            System.out.println("connected");
            String Name= nameoftrip.getText();
            String date=Dateoftrip.getText();
            String ID= idoftrip.getText();
            
            String category= jComboBox2.getSelectedItem().toString();
            String number_client=numberofclient.getText();
            int totalnumber=0;
            String price=priceoftrip.getText();
            int profit=totalnumber*Integer.parseInt(price);
            String tour_guide=jComboBox1.getSelectedItem().toString();
            
            String sql="insert into trip values('"+ID+ "','"+date+"','"+category+"','"+Name+"','"+tour_guide+"','"+number_client+"','"+totalnumber+"','"+price+"','"+profit+"')";
             statment= conn.createStatement();
             statment.execute(sql);
            query="UPDATE `tourguide` SET `isavailable`=0 where name='"+tour_guide+"'";
            statment= conn.createStatement();
            statment.execute(query);
            System.out.println("tour is added");
            Login login=new Login();
            dispose();
            login.show();
            } 
            
            
            catch (SQLException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{
                try{
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }*/
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_tour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dateoftrip;
    private javax.swing.JTextField idoftrip;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nameoftrip;
    private javax.swing.JTextField numberofclient;
    private javax.swing.JTextField priceoftrip;
    // End of variables declaration//GEN-END:variables
}
