/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import static project.Edit_tourguide.statment;
import static project.Employee.query;

/**
 *
 * @author Admin
 */
public class CancelRegistration extends javax.swing.JFrame {

    /**
     * Creates new form CancelRegistration
     */
    public CancelRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel1.setText("ID of Client");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 101, 38));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 91, 136, 37));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 160, 130, 40));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel2.setText("Name of Trip");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 164, 120, 30));

        jButton1.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 114, 40));

        jButton2.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jButton2.setText("view");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 80, 40));

        jButton3.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 388, 90, 30));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel4.setText("Cancel Registration");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 260, 53));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\back4.jpeg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 2, 390, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 static Connection conn;
    static Statement statment;
    static String query;
    sqlconn con=sqlconn.getconnection();
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed
/*public void change_trips(String name_of_trip)
{
 try{
   conn=con.connect();
   query="select totalNumber,price from trip where name='"+name_of_trip+"'";
   statment=conn.createStatement();
    ResultSet rs=statment.executeQuery(query);
    rs.next();
    int new_totalnumber=rs.getInt("totalNumber")-1;
    double new_profit=rs.getInt("price")* new_totalnumber;
    String sql="update trip set totalNumber='"+new_totalnumber+"',totalProfit='"+new_profit+"' where name='"+name_of_trip+"'";
   statment= conn.createStatement();
   statment.execute(sql);
   query="select money,Name from client where ID='"+jTextField1.getText()+"'";
   statment=conn.createStatement();
    ResultSet rs2=statment.executeQuery(query);
    rs2.next();
    String nameclient=rs2.getString("Name");
    int new_money=rs2.getInt("money")+rs.getInt("price");
    sql="update client set money='"+new_money+"' where Name='"+nameclient+"'";
   statment= conn.createStatement();
   statment.execute(sql);
    
            
   
    }      catch (SQLException ex) {   
            Logger.getLogger(CancelRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }   
}*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        
       
        Trips t;
        t = new Trips() {
            @Override
            public void getDetails_forClient(String name) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public double income_for_each_category() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        };
        
        //Client c=new Client();
        //c.cancel(jComboBox1.getSelectedItem().toString());
        
        try{
            conn=con.connect();
            t.change_trip(jComboBox1.getSelectedItem().toString(), Integer.valueOf(jTextField1.getText()));
            //change_trips(jComboBox1.getSelectedItem().toString());
            query="DELETE FROM `clienttrip` WHERE NameTrip='"+jComboBox1.getSelectedItem().toString()+"'";
            statment=conn.createStatement();
            statment.execute(query);
            
        } catch (SQLException ex) {
            Logger.getLogger(CancelRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Client c=new Client();
        c.setId(Integer.valueOf(jTextField1.getText()));
        String[] name=c.clientTrip(c);
        for(int i=0;i<name.length;i++)
        {
            jComboBox1.addItem(name[i]);
        }
        
        
        
        
        
        /*try{
            conn=con.connect();
            query="select Name from client where ID='"+jTextField1.getText()+"'";
            statment=conn.createStatement();
            ResultSet rs=statment.executeQuery(query);
            rs.next();
            String name=rs.getString("Name");
            System.out.println(name);
            DateTimeFormatter dtf=DateTimeFormatter.ofPattern("yyy-MM-dd");
            LocalDate Now=LocalDate.now();
            query="select NameTrip,Date from clienttrip where NameClient='"+name+"'";
            statment=conn.createStatement();
            ResultSet rs2=statment.executeQuery(query);
            
            while(rs2.next())
            {
                Date date=rs2.getDate("Date");
                
                if (Now.isBefore(date.toLocalDate())) {
                   
                   jComboBox1.addItem(rs2.getString("NameTrip"));    
            }
                else if (Now.isEqual(date.toLocalDate()))
                {
                    jComboBox1.addItem(rs2.getString("NameTrip"));
                }
                System.out.println("trip is previous");
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(CancelRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        Menu_client mc= new Menu_client();
        mc.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
