/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static project.Add_tour.conn;
import static project.Cancel_trip.query;
import static project.Edit_account.conn;

/**
 *
 * @author Admin
 */
public class Edit_tour extends javax.swing.JFrame {

    /**
     * Creates new form Edit_tour
     */
    public Edit_tour() {
        initComponents();
        
        /*Trips t= new Trips() {
            @Override
            public void getDetails_forClient(String name) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public double income_for_each_category() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        };
                int[] id= t.get_id_oftrip();
                for(int i=0;i<id.length;i++)
                {
                    jComboBox1.addItem(String.valueOf(id[i]));
                }*/
                
        try
         {
            sqlconn con=sqlconn.getconnection();
            conn=con.connect();
            System.out.println("connected");
            query="select ID from trip";
            statment=conn.createStatement();
            ResultSet rs= statment.executeQuery(query);
            while(rs.next())
            {   
                jComboBox1.addItem(rs.getString("ID"));  
            }
         }
         catch(SQLException ex)
         {
             System.out.println(ex.getMessage());
         }
    }
    static Connection conn;
    static Statement statment;
    static String query;
     sqlconn con=sqlconn.getconnection();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dateoftrip = new javax.swing.JTextField();
        numberclient = new javax.swing.JTextField();
        pricetrip = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setText("Update Tour");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 11, 193, -1));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 58, 69, 19));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel4.setText("Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 83, 148, -1));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel5.setText("Number of pepole");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 125, 160, -1));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel6.setText("price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 167, 148, -1));

        jButton1.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 225, -1, -1));
        getContentPane().add(dateoftrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 85, 107, 22));
        getContentPane().add(numberclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 127, 107, 22));
        getContentPane().add(pricetrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 167, 107, 24));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 54, 107, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 317, 87, 33));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\back4.jpeg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -3, 420, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        try
         {
            
            conn=con.connect();
            System.out.println("connected");
           String id= jComboBox1.getSelectedItem().toString();
            query="select price ,Date,NumberOftourist from trip where ID='"+id+"'";
            statment=conn.createStatement();
            ResultSet rs= statment.executeQuery(query);
            rs.next();
            dateoftrip.setText(rs.getString("Date"));
            numberclient.setText(rs.getString("NumberOftourist"));
            pricetrip.setText(rs.getString("price"));
         }
         catch(SQLException ex)
         {
             System.out.println(ex.getMessage());
         }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id= jComboBox1.getSelectedItem().toString();
        if(evt.getSource()==jButton1){
            Trip_Factory  tf= new Trip_Factory();
            try{
                query="select gategory from trip where ID='"+jComboBox1.getSelectedItem().toString()+"'";
                statment=conn.createStatement();
            ResultSet rs= statment.executeQuery(query);
            rs.next();
            
            Trips t=tf.Get_Trip(rs.getString("gategory"));
            t.setId(Integer.valueOf(jComboBox1.getSelectedItem().toString()));
            t.setDate(dateoftrip.getText());
            t.setPrice(Integer.valueOf( pricetrip.getText()));
            t.setNumber_of_tourists(Integer.valueOf( numberclient.getText()));
            Employee emp= new Employee();
            emp.editTrip(t);
            } catch (SQLException ex) {
                Logger.getLogger(Edit_tour.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        /*if(evt.getSource()==jButton1)
        {
            try{
            
            conn=con.connect();
            System.out.println("connected");
            String date= dateoftrip.getText();
            String number_tourist= numberclient.getText();
            String price= pricetrip.getText();
            String sql="update trip set Date='"+date+"',NumberOftourist='"+number_tourist+"'"
                    + ",price='"+price+"' where ID='"+id+"'";
             statment= conn.createStatement();
             statment.execute(sql);
            
            System.out.println("trip is updated");
            Menu_client mc=new Menu_client();
            dispose();
            mc.show();
            } 
            
            
            catch (SQLException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{
                try{
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }}*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        manage_trip m= new manage_trip();
        m.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_tour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dateoftrip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField numberclient;
    private javax.swing.JTextField pricetrip;
    // End of variables declaration//GEN-END:variables
}
